In [13]:
import numpy as np

t1 = list(map(int, input().split(",")))
t2 = list(map(int, input().split(",")))

In [14]:
V1 = np.array(t1)
V1


array([1, 2, 3, 4])

In [15]:
V2 = np.array(t2)
V2

array([10, 20, 30, 40])

In [16]:
V3 = V1 + V2
V3

array([11, 22, 33, 44])

In [17]:
V4 = V1[::2] * V2[::-2]
V4

array([40, 60])