6.3.1

In [1]:
import numpy as np

6.3.2

In [2]:
print(np.__version__)

1.17.2


6.3.3

In [5]:
n = int(input())
Z = np.zeros(n)

6.3.4

In [31]:
n = input().split()
dtype = np.dtype(np.float64)
if n[-1].isalpha():
    dtype = np.dtype(n[-1])
    shape = tuple(list(map(int,n[:-1])))
else:
    shape = tuple(list(map(int, n)))
Z = np.zeros(shape, dtype=dtype)

6.3.5

In [32]:
Z = Z.size * Z.itemsize

6.3.6

In [44]:
?np.add.__doc__
?np.array.__doc__

6.3.7

In [47]:
n, x = int(input()), int(input())
Z = np.zeros(n)
Z[x] = 1
Z

array([0., 0., 0., 0., 1., 0., 0., 0., 0., 0.])

6.3.8

In [49]:
Z = np.array([i for i in range(int(input()),int(input())+1)])

6.3.9

In [50]:
Z = Z[::-1]

6.3.10

In [55]:
n = int(input())
m = input().split()
m = list(map(int, m))
Z = np.arange(n).reshape(m[0],m[1])

6.3.11

In [ ]:
NonZerros = np.nonzero(Z)

6.3.12

In [89]:
x = np.nonzero(Z>3)
k =list(x)
k = np.array(k)
print(k)
print(x[0][2], x[1][2])
print(Z[x[0][2]][x[1][2]])

[[1 1 2 2 2]
 [1 2 0 1 2]]
2 0
6
