In [1]:
import numpy as np
from urllib.request import urlopen

In [2]:
mat = 2*np.eye(3,4) + np.eye(3,4,1)
print(mat)

[[2. 1. 0. 0.]
 [0. 2. 1. 0.]
 [0. 0. 2. 1.]]


In [3]:
mat = mat.reshape((12,1))
print(mat)

[[2.]
 [1.]
 [0.]
 [0.]
 [0.]
 [2.]
 [1.]
 [0.]
 [0.]
 [0.]
 [2.]
 [1.]]


In [4]:
x_shape = tuple(map(int, input().split()))
X = np.fromiter(map(int, input().split()), np.int).reshape(x_shape)
y_shape = tuple(map(int, input().split()))
Y = np.fromiter(map(int, input().split()), np.int).reshape(y_shape)
if x_shape[-1]!= y_shape[-1]:
    print("matrix shapes do not match")
else:
    Y = Y.transpose()
    print(X.dot(Y))

ValueError: cannot reshape array of size 0 into shape ()

In [5]:
f = urlopen('https://stepic.org/media/attachments/lesson/16462/boston_houses.csv')
z = np.loadtxt(f, skiprows=1, delimiter=",")
k = np.loadtxt("boston_houses.csv", skiprows=1, delimiter=",")
v = z.mean(axis=0)
print(v)

[22.53280632  3.61352356 11.36363636  0.06916996  0.55469506  6.28463439
  3.79504269]


In [7]:
u = np.array([[1.,60.],[1.,50.],[1.,75.]])
a = np.array([10.,7.,12.])
ui = u.T @ u
d = np.linalg.inv(ui)
c = d @ u.T
j = c @ a.T

In [22]:
#fname = input() 
f = urlopen('https://stepic.org/media/attachments/lesson/16462/boston_houses.csv')
z = np.loadtxt(f, skiprows=1, delimiter=",")
t = np.copy(z)
firs = t[:,0]
z[:,0] = 1
xtx = z.T @ z
xtx_inv = np.linalg.inv(xtx)
xty = z.T @ firs
b = xtx_inv @ xty
print(*b)

-3.655804285049271 -0.21639550236914573 0.07373059817549987 4.412450576913194 -25.468448784106613 7.14320155074488 -1.301087677649349


In [2]:
from math import exp
#Функция гиперболического тангенса
def tanh(x):
    return ((exp(x)-exp(x*-1))/(exp(x)+exp(x*-1)))

#Сигмоидальная функция
def sigm(x):
    return 1/(1+(exp(x*-1)))

#Производная гиперболического тангенса
def dtanh(x):
    return ( (1-exp(x-2))**2    *    (-(exp(x-2)+1))**2 ) +1

#Производная сигмоидальной функции
def dsigm(x):
    return ( exp(-x)/(exp(-x)+1)**2 )


#Принт вариантов ответов по почереди подбирая Х

x=0

#1. производная tanh в точке 0 и производная σ в точке 0
print (f'd tanh({x})={dtanh(x)}\nd sigm({x})={dsigm(x)}')

#2. tanh(−x)=1−tanh(x) для любого x
print (f'\ntanh(-x)={tanh(-x)}')
print ('1−tanh(x)=',(1-tanh(x)))

#3 σ(−x)=−σ(x) для любого x (сигмоидальная функция нечётна)
print (f'\nsigm(-x)={sigm(-x)}\n−sigm(x)={-sigm(x)}')

#4. σ(−x)=1−σ(x) для любого x
print (f'\nsigm(-x)={sigm(-x)}\n1-sigm(x)={1-sigm(x)}')

#5 tanh(−x)=−tanh(x) для любого x (гиперболический тангенс нечётен)
print (f'\ntanh(-x)={tanh(-x)}\n-tanh(x)={-tanh(x)}')

d tanh(0)=1.9637041848504344
d sigm(0)=0.25

tanh(-x)=0.0
1−tanh(x)= 1.0

sigm(-x)=0.5
−sigm(x)=-0.5

sigm(-x)=0.5
1-sigm(x)=0.5

tanh(-x)=0.0
-tanh(x)=-0.0
